language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t serezha/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true serezha/docker-react npm run test
